In [ ]:
import cv2

In [ ]:
img = cv2.imread(r"D:\bharat\Images\thor_green.png")
img = cv2.resize(img, (500,500))
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

img1 = cv2.imread(r"D:\bharat\Images\green.png")
hsv2 = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)

hist = cv2.calcHist([hsv2],[0,1],None,[180,256],[0,180,0,256])
mask = cv2.calcBackProject([hsv],[0,1],hist,[0,180,0,256],1)

ker = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
mask = cv2.filter2D(mask,-1,ker)

_,th = cv2.threshold(mask,200,255,cv2.THRESH_BINARY)

mask = cv2.merge((mask,mask,mask))

res = cv2.bitwise_or(img,mask)



# res = cv2.bitwise_or(img,img,mask = mask)


cv2.imshow("ws",res)
cv2.imshow("wscube",img)
# cv2.imshow("wscube1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Hough Transformation Lines

In [ ]:
import cv2
import numpy as np

In [ ]:
img =  cv2.imread(r"D:\bharat\Images\soduku.webp")
# img = cv2.resize(img,(500,500))

img1 = cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)

edg = cv2.Canny(img1,20,250)
#Desgin hough lines
lines = cv2.HoughLines(edg,1,np.pi/180,200)

# print(lines)
for r,th in lines[0]:
    a = np.cos(th)
    b = np.sin(th)
    
    x0 = a*r
    y0 = b*r
    
    x1 = int(x0+1000*(-b))
    y1 = int(y0+1000*(a))
    x2 = int(x0-1000*(-b))
    y2 = int(y0-1000*(a))
    
    cv2.line(img, (x1,y1),(x2,y2),(0,255,0), 2)


cv2.imshow("window",img)
cv2.imshow("window1",edg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img =  cv2.imread(r"D:\bharat\Images\soduku.webp")
# img = cv2.resize(img,(500,500))

img1 = cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)

edg = cv2.Canny(img1,20,250)
#Desgin hough lines
l = cv2.HoughLinesP(edg,1,np.pi/180,200,minLineLength = 180,maxLineGap = 100)

for i in l:
    x1,y1,x2,y2 = i[0]
    cv2.line(img, (x1,y1),(x2,y2),(0,255,0), 2)
    
cv2.imshow("window",img)
# cv2.imshow("window1",edg)
cv2.waitKey(0)
cv2.destroyAllWindows()
    

# Template Matching 

In [ ]:
import cv2
import numpy as np

In [ ]:
img = cv2.imread(r"D:\bharat\Images\test_image.jpg")
gry =cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)


img1 = cv2.imread(r"D:\bharat\Images\test_image1.jpg")
gry1 =cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)

w,h = gry1.shape[1],gry1.shape[0]
res = cv2.matchTemplate(gry,gry1,cv2.TM_CCORR_NORMED)
print(res)
thr = .9

l =  np.where(res>=thr)

for i in zip(*l[::-1]):
    cv2.rectangle(img,i,(i[0]+w,i[1]+h),(0,255,0),2)
    
    
    
img = cv2.resize(img,(500,500))

# print(l)

# print(res)
cv2.imshow("window" , img)
cv2.imshow("window1",img1)
cv2.imshow("window2", res)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
w,h

In [ ]:
print(res)

# Grabcut Algorithm for Background Change

In [6]:
import cv2
import numpy as np

In [5]:
img = cv2.imread(r"D:\bharat\Images\mikebirdy.jpg")
# print(img)
# img = cv2.resize(img, (500,600))


mask1 = np.zeros(img.shape[:2],np.uint8)
# print(mask1)
bgmask = np.zeros((1,65),np.float64)
fgmask = np.zeros((1,65),np.float64) 


r = (596,701,3534,2462)
cv2.grabCut(img,mask1,r,bgmask,fgmask,10,cv2.GC_INIT_WITH_RECT)

mask2 =np.where((mask1 == 2)|(mask1 == 0),0,1).astype("uint8")
print(mask2)
img = img*mask2[:,:,np.newaxis]
print(img)
cv2.imshow("window",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [119 135 141]
  [115 131 137]
  [113 129 135]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [118 134 140]
  [115 131 137]
  [113 129 135]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [120 136 142]
  [118 134 140]
  [118 134 140]]]


In [7]:
import cv2
import numpy as np

# Load and resize the image
img = cv2.imread(r"D:\bharat\Images\mikebirdy.jpg")
img = cv2.resize(img, (500, 600))

# Initialize the mask, background model, and foreground model
mask1 = np.zeros(img.shape[:2], np.uint8)
print(mask1)
bgmask = np.zeros((1, 65), np.float64)
fgmask = np.zeros((1, 65), np.float64)

# Define the rectangle for the grabCut algorithm
rect = (50, 50, 400, 500)  # Adjust these values as per the area of interest

# Apply the grabCut algorithm
cv2.grabCut(img, mask1, rect, bgmask, fgmask, 10, cv2.GC_INIT_WITH_RECT)

# Modify the mask such that all the 0 and 2 pixels are put to 0, and others are put to 1
mask2 = np.where((mask1 == 2) | (mask1 == 0), 0, 1).astype('uint8')
print(mask2)
# Multiply the input image with new binary mask to get the segmented image
img = img * mask2[:, :, np.newaxis]
print(img)

# Display the result
cv2.imshow("window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
